### ISSUE TITLE
after booting, cora board loops on PHY autonegotiation

### ISSUE THREAD

**Issue by flynneva** [Digilent/Cora-Z7-OS#2]
seems like the board is stuck during boot up on the PHY auto-negotiation phase of the process.

any tips on how to get it 'un-stuck' or set some sort of maximum attempts?

**Comment by flynneva** [comment]
for some help with debugging....here is what im seeing as an output from the cora 07S board via minicom:

```
Flash: 0 Bytes                                                           
NAND:  0 MiB                                                                    
MMC:   mmc@e0100000: 0                                                          
In:    serial@e0000000                                                          
Out:   serial@e0000000                                                          
Err:   serial@e0000000                                                          
Net:                                                                            
ZYNQ GEM: e000b000, mdio bus e000b000, phyaddr 1, interface rgmii-id            
                                                                                
Warning: ethernet@e000b000 using MAC address from DT                            
eth0: ethernet@e000b000                                                         
U-BOOT for Cora Z7                                                              
26 bytes read in 16 ms (1000 Bytes/s)                                           
ethernet@e000b000 Waiting for PHY auto negotiation to complete...
```

it hangs on that for a while and then eventually prints out this:
```
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
## Executing script at 03000000
Wrong image format for "source" command
SCRIPT FAILED: continuing...
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
MMC Device 1 not found
no mmc device at slot 1
Warning: SPI speed fallback to 100 kHz
unrecognized JEDEC id bytes: 00, 00, 00
Failed to initialize SPI flash at 0:0 (error -2)
SCRIPT FAILED: continuing...


no devices available
SCRIPT FAILED: continuing...
## Executing script at 03000000
Wrong image format for "source" command
SCRIPT FAILED: continuing...
starting USB...
Bus usb@e0002000: USB EHCI 1.00
scanning bus usb@e0002000 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device

Device 1: unknown device
ethernet@e000b000 Waiting for PHY auto negotiation to complete.....
```

**Comment by flynneva** [comment]
so i tried booting with the ethernet cable plugged into my workstation and the output is a bit different.

**Comment by ionel-badisor** [comment]
Make sure `boot.scr` is copied on SD card and that you have at least 1 partition on SD Card.

**Comment by flynneva** [comment]
I only copied over BOOT.bin and image.ub over to my SD card which has two partitions - one FAT and one EXT4.

I put both BOOT.bin and image.ub in the FAT partition. should this also be where the boot.scr  file goes?

I was following [this article by Rich Arthurs](https://richarthurs.com/2019/01/05/cora-linux-getting-started/) and [the readme instructions here](https://github.com/Digilent/Petalinux-Cora-Z7-07S) originally...but modified it to fit this new os submodule structure for 2020.1.

**Comment by ionel-badisor** [comment]
Yes the first partition is fat32 and should have 3 files: BOOT.bin, boot.scr and image.ub.
u-boot looks for boot.scr in mmc 0:1 which contains instructions to load the kernel from image.ub.
If boot.scr is missing u-boot will try to boot from USB or network so it is scanning for other boot media. That is what you see in the log.

**Comment by flynneva** [comment]
progress! got it working by copying over the `boot.src` file. getting a terminal over serial output now after booting.

thanks so much for your tips!
